// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2core.Models;

namespace WebApplication2core.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200524140320_order")]
    partial class order
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplication2core.Models.Cart", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("grandTotal");

                    b.Property<int?>("userId");

                    b.Property<long>("user_id");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("WebApplication2core.Models.CartProduct", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("cart_id");

                    b.Property<long?>("cartid");

                    b.Property<long>("product_id");

                    b.Property<long?>("productid");

                    b.HasKey("id");

                    b.HasIndex("cartid");

                    b.HasIndex("productid");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("WebApplication2core.Models.Category", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebApplication2core.Models.Order", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("cart_id");

                    b.Property<long?>("cartid");

                    b.Property<bool>("completed");

                    b.Property<int?>("userId");

                    b.Property<long>("user_id");

                    b.HasKey("id");

                    b.HasIndex("cartid");

                    b.HasIndex("userId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebApplication2core.Models.Product", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("category_id");

                    b.Property<long?>("categoryid");

                    b.Property<string>("content")
                        .IsRequired();

                    b.Property<string>("fullContent");

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<double>("price");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebApplication2core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WebApplication2core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<int?>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication2core.Models.Cart", b =>
                {
                    b.HasOne("WebApplication2core.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("WebApplication2core.Models.CartProduct", b =>
                {
                    b.HasOne("WebApplication2core.Models.Cart", "cart")
                        .WithMany("cartProducts")
                        .HasForeignKey("cartid");

                    b.HasOne("WebApplication2core.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productid");
                });

            modelBuilder.Entity("WebApplication2core.Models.Order", b =>
                {
                    b.HasOne("WebApplication2core.Models.Cart", "cart")
                        .WithMany()
                        .HasForeignKey("cartid");

                    b.HasOne("WebApplication2core.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("WebApplication2core.Models.Product", b =>
                {
                    b.HasOne("WebApplication2core.Models.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("categoryid");
                });

            modelBuilder.Entity("WebApplication2core.Models.User", b =>
                {
                    b.HasOne("WebApplication2core.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
